### ISSUE TITLE
Method Laravel\Scout\Builder::limit does not exist.

### ISSUE THREAD

**Issue by Cannonb4ll** [shokme/laravel-scout-meilisearch#10]
Hi,

It seems the `limit()` option is not available, if I read the documentation it seems it should be available.

```php
$items = FaqItem::search(request('query'))->limit(5)->get();
```

Returns me with an error:

```
exception: "BadMethodCallException"
file: "/Users/***/Workspace/***/vendor/laravel/framework/src/Illuminate/Support/Traits/Macroable.php"
line: 103
message: "Method Laravel\Scout\Builder::limit does not exist."
```

Is there something I am missing, or is this method missing from the package?

**Comment by SamuelNitsche** [comment]
I think the documentation is wrong here. Correct would be the following:
```
$items = FaqItem::search(request('query'))->take(5)->get();
```

**Comment by Cannonb4ll** [comment]
`take()` will work indeed, but does that make actual use of the limit function in the meilisearch API?

https://docs.meilisearch.com/guides/advanced_guides/search_parameters.html#limit

**Comment by SamuelNitsche** [comment]
I think it is. See [https://github.com/meilisearch/meilisearch-laravel-scout/blob/master/src/Engines/MeilisearchEngine.php#L92](https://github.com/meilisearch/meilisearch-laravel-scout/blob/master/src/Engines/MeilisearchEngine.php#L92)

**Comment by Cannonb4ll** [comment]
Yeah I have noticed that, then the documentation is indeed not correct I recon.

**Comment by shokme** [comment]
You have right, my mistake `take()` is the correct one !
And to confirm yes the $builder->limit works has expected when using `take()`

I will update the doc ;)
Thank you!

**Comment by Cannonb4ll** [comment]
Keep up the awesome work 🚀
