### ISSUE TITLE
cant find any good example tutorial  ,correct me if iam doing wrong 

### ISSUE THREAD

**Issue by NatBLida68** [shokme/laravel-scout-meilisearch#110]
With formal knowledge  in  creating custom search engine for one of my project i managed to make it work 
idk this is the right way to use it if not please  advise 
i have multiple models with one common field row_no in each .
first installed meilisearch  using curl and run on 127.0.0.1:7700   then i added this module using composer and published  and 
created indexes and imported all data 
from given code samples search is from individual model  since i have multiple models and want to use single search function  
i found    `meilisearch /meilisearch-php  ` as useful   and added  a dropdown to select facet during search  and i change index dynamically on selected facet 
```
$client = new Client('http://127.0.0.1:7700', 'key');
        $index = $client->index($index);
```
this is working as expected   but is there any simple way without using  `meilisearch /meilisearch-php `
api and cdn are not fit for me  and i don't like to include node modules in this simple project 
any alternatives ?

**Comment by curquiza** [comment]
Hello @NatBLida68!

I'm not sure to really understand your usecase.
Are you using the Laravel Scout extension (= this repo)?
This repos already uses `meilisearch/meilisearch-php` so I'm not sure to get why you don't want to include it. Sorry if I miss something.
If your issue is to update the MeiliSearch settings using this repo, you might want to check this wiki -> https://github.com/meilisearch/meilisearch-laravel-scout/wiki/Indexes-settings-using-model

Sorry again if I miss something, tell me if I'm not clear enough 🙂

**Comment by NatBLida68** [comment]
@curquiza  sorry I'm new here and still learning coding  ,   at first yes I'm using this repo  (the scout extension)   but in my project  i have included  this repo `(meilisearch-laravel-scout)` and `meilisearch/meilisearch-php`  separately  and  for importing data iam using  Searchable trait and  scout:import  this is only where this repo have use .   and then for searching purpose i iam using `MeiliSearch\Client` from `meilisearch/meilisearch-php`   with this code 
```
$client = new Client('http://127.0.0.1:7700', 'mykey');
        $index = $client->index($index);
$hits = $index->search($key)->getHits();
```
i have to make sure it is the right way to do this ,   that is do i have to add meilisearch-php  separately  or this repo have included it

**Comment by curquiza** [comment]
No problem, we all are here to learn 😁
This is indeed the right way to search in your index if you use only `meilisearch/meilisearch-php`.
However, if you use `meilisearch-laravel-scout` you can search using this:
- a basic search (to follow you example) -> https://github.com/meilisearch/meilisearch-laravel-scout#search-in-an-index-
- a custom search (what you might want in the future) -> https://github.com/meilisearch/meilisearch-laravel-scout#search

Plus here are some docs about the search parameter to guide you through your custom search -> https://docs.meilisearch.com/reference/features/search_parameters.html#search-parameters

**Comment by NatBLida68** [comment]
@curquiza   thanks for helping
