### ISSUE TITLE
The future of this repo

### ISSUE THREAD

**Issue by curquiza** [shokme/laravel-scout-meilisearch#111]
Hello everyone,

With @shokme (the main author of this package) we decided for the plan of this repository to build an integration for Laravel Scout by staying completely compliant/conformed with the [original `laravel/scout` package](https://github.com/laravel/scout). 

The goal? To integrate this repository into the official `laravel/scout` package ([as Algolia already is](https://github.com/laravel/scout#introduction)) by showing that people use it. We are working on this. We’ll keep you informed.

What does it mean? We did not integrate any contributions that would make the usage differ from the scout usage. Like [this PR](https://github.com/meilisearch/meilisearch-laravel-scout/pull/109). The settings have to be handled in your models like we described in [our wiki](https://github.com/meilisearch/meilisearch-laravel-scout/wiki/Indexes-settings-using-model).

However, we would understand some of you would like a laravel-scout-extended integration, I mean with more friendly methods to handle settings in this repository, [as this PR suggests](https://github.com/meilisearch/meilisearch-laravel-scout/pull/109).

The question: **what do you think about making this repo an extended package and not only a strict integration with laravel-scout as we have right now?**
For example, Algolia also did it with their [`scout-extended` package](https://github.com/algolia/scout-extended).

I’m not saying it would be a priority task or an immediate and drastic change, we are not even sure this is the right choice to do, but we deeply believe it’s a good thing to have the community's opinion in mind when making decisions for the future of our repositories.
The PHP community is one of our most involved communities around MeiliSearch and all the Meili team would like to thank you for this! ❤️ Hope we will have your opinion here!

**Comment by mmachatschek** [comment]
@curquiza 
I'm also a fan of this idea. There were already some PRs and issues related to extending this package. Providing a similar package as scout-extended for algolia would make the DX of MeiliSearch much better

**Comment by curquiza** [comment]
Got it! The first step for me will be to create an issue in the `laravel/scout` repo to check if the maintainers are ok to integrate us.
Once they are ok, we have to do a PR on the `laravel/scout` repo, and I'm not sure the integration team will have time to do it soon...
And finally, once we have been integrated into `laravel/scout` (🤞) we should start thinking (and implementing) about how to improve this package. I think checking what Algolia did in `scout-extended` is a good start 😄

**Comment by curquiza** [comment]
And thanks @mmachatschek for your return!! 😄

**Comment by mmachatschek** [comment]
@curquiza I already created a branch to add support for meilisearch here https://github.com/mmachatschek/scout/tree/add_meilisearch_support

As soon as you created the issue on the repo in the name of MeiliSearch I'll send in the PR

**Comment by mmachatschek** [comment]
@curquiza also I think that if the current state of this repo will be merged into laravel/scout this should be deprecated and a new repo should be created.
This package is not tagged as > 1.x and breaking changes can be introduced. But the main purpose of this package (creating a MeiliSearch client for laravel/scout) is not met anymore.

**Comment by curquiza** [comment]
Thank you so much for your involvement @mmachatschek!! ❤️ 

I will discuss with the Meili team what to do with this repo next. I'm sad about giving up the most stared repository in the MeiliSearch integrations, even if 400 ⭐️ is not that much 😂  but you're right, it does not fit the first need.

I'll keep you informed.

**Comment by shokme** [comment]
@mmachatschek you rock :smile:

**Comment by curquiza** [comment]
I've just asked laravel/scout-> https://github.com/laravel/scout/issues/454
🤞

**Comment by driesvints** [comment]
We've just released Scout v9.0 with Meilisearch support.

**Comment by curquiza** [comment]
Thank you so much @driesvints! 😁 All the Meili team is really excited by this news!

**Comment by driesvints** [comment]
@mmachatschek did the bulk of the work 🙂

**Comment by shokme** [comment]
@curquiza So, what's the next step ?
how will we "deprecate" this package ?

**Comment by curquiza** [comment]
@shokme, before doing anything I would like to have your opinion on this: do you think this is better to deprecate this repo and create a new one instead of "transforming" it?

I already have your opinion on this question @mmachatschek 😉 https://github.com/meilisearch/meilisearch-laravel-scout/issues/111#issuecomment-802633375

If anyone has any opinion to share, don't hesitate 🙂

**Comment by shokme** [comment]
Indeed, I think this is better to deprecate this repo and create a new one.

**Comment by curquiza** [comment]
I will discuss with the Meili team how to do this, and I will come back asap.
FYI, we don't currently have the human resources (at Meili) to create an extended integration for laraval scout (like [this one](https://github.com/algolia/scout-extended)), but the integration in the official laravel/scout should be enough for the moment 🙂

**Comment by shokme** [comment]
@curquiza I understand. I'm still available to contribute if needed while keeping an eye open on the laravel/scout issues.

**Comment by curquiza** [comment]
We have officially decided to deprecate this repo. I'm closing this issue and I open this one! I'm going to archive this repo 🙂
Thank you everyone for your help, we are lucky to have a community as involved as you are ❤️
