### ISSUE TITLE
Delay for index new records

### ISSUE THREAD

**Issue by ibrunotome** [shokme/laravel-scout-meilisearch#113]
I think I'm facing this problem https://github.com/meilisearch/MeiliSearch/issues/1098

With artisan command, everything works fast, but for new records saved on database it's taking maybe more than an hour to appears on MeiliSearch web UI.

[edit]

I have two models with Searchable trait: User model and Order model. All new models of User are indexed at same time they are created, but all new models of Order are taking this long time 🤔  

This is my User searchable array:
<img width="385" alt="Screen Shot 2021-03-12 at 17 42 54" src="https://user-images.githubusercontent.com/4256471/110996219-65042d80-835a-11eb-9321-f020f48e066d.png">

This is my Order searchable array:
<img width="799" alt="Screen Shot 2021-03-12 at 17 44 07" src="https://user-images.githubusercontent.com/4256471/110996329-8d8c2780-835a-11eb-9a4c-a1b61dfd736e.png">

**Comment by curquiza** [comment]
Hello @ibrunotome 

It looks like it's not a laravel issue but indeed a MeiliSearch one (it seems like you linked the good issue).
Sorry for this, we (the core team in meili) are currently working on a new search engine way more performant. I hope it will solve this issue.
Closing this issue then
