### ISSUE TITLE
[DX] Easy index configuration

### ISSUE THREAD

**Issue by robsontenorio** [shokme/laravel-scout-meilisearch#114]
Hi, thanks for your time!

Just noticed on wiki page some alternative to configure indexes. But i think it adds a extra boilerplate to the project. 

Suggestions for simplicity about config meilisearch index:

- Via Model, using a protected property as array representing the “index config”, with same options as described on wiki page. 

- Via config/meilisearch.php file, with the same options as described on wiki page.

**Comment by mmachatschek** [comment]
Hi @robsontenorio,

this is something that would be solved by issue #111. This package aims to provide the same functionallity as the Algolia client provided by [laravel/scout](https://github.com/laravel/scout/blob/8.x/src/Engines/AlgoliaEngine.php). You are right. your suggestions would definitely solve some common uses cases of many users of MeiliSearch

**Comment by curquiza** [comment]
Hello @robsontenorio!

@mmachatschek perfectly explained the situation, and you're right this is the kind of improvement we would add :)
