### ISSUE TITLE
Update of existing records

### ISSUE THREAD

**Issue by hope22** [shokme/laravel-scout-meilisearch#124]
I have meilisearch working via Laravel Forge on its own dedicated ec2 instance.

Everything works great.

Apart from when a record is updated `via ->save()` eloquent method.

The record on the meilisearch server doesn't change.
> I'm updating via amazon sqs queues.

I've been checking this via Postman by doing a direct get request to the server and the records just don't update.

I've hit a dead end in my debugging and wondering if anyone else has a similar issue or there is just a big delay when updating records.

## Update
It seems to be the tasks taking **up to 5 hours** to process a document update.
Not sure why this is taking so long or if there is a way I can assign more processes to this process?

```
{
    "status": "processed",
    "updateId": 11022,
    "type": {
        "name": "DocumentsAddition",
        "number": 1
    },
    "duration": 47.64718841,
    "enqueuedAt": "2021-04-17T11:10:20.522991788Z",
    "processedAt": "2021-04-18T17:43:41.904437172Z"
}
```

**Comment by hope22** [comment]
Done some digging into the API and seen some of the updates are getting the following error:

```
{
    "status": "failed",
    "updateId": 0,
    "type": {
        "name": "DocumentsAddition",
        "number": 1
    },
    "error": "document id is missing",
    "errorType": "invalid_request_error",
    "errorCode": "missing_document_id",
    "errorLink": "https://docs.meilisearch.com/errors#missing_document_id",
    "duration": 0.000860604,
    "enqueuedAt": "2021-04-16T17:27:19.299672712Z",
    "processedAt": "2021-04-16T17:27:19.303733835Z"
}
```

**Comment by hope22** [comment]
They seem to be stuck at this status, a few updating every few minutes with a huge backlog.

```
{
    "status": "enqueued",
    "updateId": 11100,
    "type": {
        "name": "DocumentsAddition",
        "number": 1
    },
    "enqueuedAt": "2021-04-17T12:28:48.694663760Z"
}
```

**Comment by curquiza** [comment]
Hello @hope22!
I see you have more than 10.000 updates, do you send them at the same time? Is one update contain only one document? You should them several documents at the same time, by batches.

**Comment by hope22** [comment]
Hey @curquiza.

I have since started batching updates in groups of 2000 which gives me faster results.
My issue seemed to be when single documents were updated they were getting backlogged.

Would be great if there was an API route to clear the black-logged updated then I can just run a fresh import again.

Apart from that, amazing product! Loving it. Well done :)

Can make as resolved.

**Comment by curquiza** [comment]
Hello @hope22!
We are thinking about adding this possibility into MeiliSearch. It will maybe be added some days :)

Thanks for your feedback! Thanks for using MeiliSearch ❤️
