### ISSUE TITLE
Getting an error when meilisearch service is not run

### ISSUE THREAD

**Issue by milosevicn** [shokme/laravel-scout-meilisearch#127]
When Meilisearch service is not running, after I try creating/updating/deleting something on a model which has `Searchable` inside it's `use`, I am facing this error:
`cURL error 7: Failed to connect to 127.0.0.1 port 7700: Connection refused (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for http://127.0.0.1:7700/indexes/pages_index`

Is there a way to keep `Searchable` in `use` and make it work with `meilisearch.service` stopped?

**Comment by mmachatschek** [comment]
Hi @milosevicn! This is not a MeiliSearch specific issue. If you know, that the MeiliSearch instance is not running, you can set the `scout.driver` setting in the environment variable to `null`. This loads a so called NULL-driver which basically ensures that everything keeps working fine, but no search results are returned if called.
