### ISSUE TITLE
Laravel native support announced

### ISSUE THREAD

**Issue by robsontenorio** [shokme/laravel-scout-meilisearch#134]
Today has been announced native support for MeiliSearch through Laravel Scout. 

So, that means this current package will be deprecated ?

https://twitter.com/driesvints/status/1387120043318779904?s=21

**Comment by curquiza** [comment]
Hello @robsontenorio, thanks for your interest! ❤️ A discussion is already opened here #111!
Feel free to give your opinion (see this comment https://github.com/meilisearch/meilisearch-laravel-scout/issues/111#issuecomment-829296501) 😁
I close this issue in favor of #111
