### ISSUE TITLE
[question] how to search in related models as well ?

### ISSUE THREAD

**Issue by ctf0** [shokme/laravel-scout-meilisearch#24]
first many thanx for this tool, its a breeze in compare to others.

i was wondering if there is a way to search in related models as well ? i know its already an issue with scout but maybe meili could have a custom search where we can also search in other indexes and merge the results.

**Comment by shokme** [comment]
Hello,

This package is just an extension of what scout does and doesn't.

I don't know if scout has a true limitation or if it can be done, do you have a link to the scout issue so I can have more information ?

**Comment by ctf0** [comment]
its an old limitation of scout which hasnt been addressed yet, u can check [google](https://www.google.com/search?q=laravel+scout+search+relation&rlz=1C5CHFA_enEG865EG865&oq=laravel+scout+search+&aqs=chrome.1.69i57j35i39j0l3j69i60j69i65j69i60.3991j0j7&sourceid=chrome&ie=UTF-8)

but i was hopping that meili would have the option to search in multiple indexes as atm i cant find anything related to this in the [docs](https://docs.meilisearch.com/guides/main_concepts/indexes.html)

**Comment by curquiza** [comment]
Hello @ctf0!

MeiliSearch cannot search in multiple indexes for the moment. But be sure we are thinking about adding this feature 😉 I'll keep you in touch!

**Comment by shokme** [comment]
Ok I let this issue open as an enhancement, we will see what we can do in few months

Thank you guys !

**Comment by flick36** [comment]
This might come in handy:

- https://github.com/algolia/scout-extended
- https://www.algolia.com/doc/framework-integration/laravel/advanced-use-cases/multiple-models-in-one-index/?language=php

**Comment by haexperts2020** [comment]
Would love to see this implemented since its free/open-souce and runs locally. For now I'll give the Algolia aggregator a try

**Comment by curquiza** [comment]
Closing this issue. If you want to be informed about MeiliSearch features here are some links:
- the roadmap: https://roadmap.meilisearch.com/tabs/5-ideas. Feel free to add features or to update the existing ones.
- the MeiliSerach repository to watch PRs and issues: https://github.com/meilisearch/MeiliSearch
- the specs repository of MeiliSearch: https://github.com/meilisearch/specifications/
