### ISSUE TITLE
Return all results when no term is provided

### ISSUE THREAD

**Issue by faustbrian** [shokme/laravel-scout-meilisearch#28]
Is there currently some way to perform a search with an empty string to simply get all results? Meaning that instead of doing a search we would simply call `getDocuments` and apply all options to that.

**Comment by shokme** [comment]
There is no way to achieve this.

But as **example** you can create or extends the `Searchable Trait` to add the following method:
```php
use MeiliSearch\Client;

public static function getDocuments($options = null)
{
    $client = app(Client::class);
    $self = new static;
    $index = $client->getIndex($self->searchableAs());

    return new Collection($self::hydrate($index->getDocuments($options)));
}
```

`app(Client::class)` is a singleton.
```php
$this->app->singleton(Client::class, function ($app) {
    return new Client(config('meilisearch.host'));
});
```

I don't know if there is a better way to achieve what you ask, but I hope it helped you :smile:

**Comment by faustbrian** [comment]
Alright, that's pretty much what I went with in a slightly different way to check if the query is empty or not.
