### ISSUE TITLE
getTotalCount returns nbHits which doesn't match total count if results have been filtered.  This breaks pagination.

### ISSUE THREAD

**Issue by isaackearl** [shokme/laravel-scout-meilisearch#34]
Right now using the documented method to get results and paginate, I always end up with alot of extra "pages" in my pagination links because when the LengthAwarePaginator is built, it uses nbHits for the total count of results.  This only works if you are not filtering at all.  Is there any way to work around this other than building my own paginator? Or finding a way to override the getTotalCount in MeilisearchEngine.php ?  

The current code is like this:
```
    public function getTotalCount($results)
    {
        return $results['nbHits'];
    }
```

If I change the getTotalCount method of MeilisearchEngine.php to something like
```
    public function getTotalCount($results)
    {
        return count($results);
    }
```

Then everything works as expected.

Any thoughts?  
for a little further information I'm doing queries like this:
```
        return Set::search($this->search, function(Index $meilisearch, $query, $options) {
           $options['filters'] = 'user_id = ' . \Auth::user()->id;
           return $meilisearch->search($query, $options);
        })->paginate($perPage);
        // or like this: 
        return Set::search($this->search)->where('user_id', \Auth::id())->paginate($perPage);
```
And even though that user only gets 5 results, the paginator shows 20 pages of blank results (since nbHits doesn't account for filtering, and the paginator uses getTotalCount method which simply returns nbHits)

I'm fairly certain this is uninteded behavior and is therefor a BUG.  would a PR to fix this be accepted?

EDIT: I realized this might be a bug in the Meilisearch library itself rather then this scout plugin.  I ran a test going back to the algolia driver (I'm trying to move away from algolia), and the code for that also return simply "nbHits".  However in the case of using Algolia, the nbHits number has been properly affected by the filter.  In other words.  nbHits for Meilisearch is not returning the correct number, and nbHits for algolia is.  Let me know if you think I should open an issue on that repo.

Thanks,
Isaac

**Comment by shokme** [comment]
Hello Isaac,
You can see this PR https://github.com/meilisearch/MeiliSearch/pull/541 and linked issues to have a bit more of context.
And for the filtering you can check this one https://github.com/meilisearch/MeiliSearch/issues/764

So, unfortunately I will not accept a PR and wait the fix from Meilisearch 😄 

I will checkout later this week-end if this is possible to override the `getTotalCount` method to avoid to interrupt your work 😄
Thank you !

**Comment by isaackearl** [comment]
@shokme yes absolutely that makes sense.  I can find some workarounds while waiting for a fix.  I didn't realize until the last moment that it is actually a bug/issue for the Meilisearch package.  Thanks!

**Comment by shokme** [comment]
Hello @isaackearl,
sorry for the delay, do you still need help to override the `getTotalCount()` ?

**Comment by isaackearl** [comment]
no problem @shokme.  No, I appreciate the offer, but no need.  I have some workarounds in place until I wait for an official fix.  In fact, simply overriding the total count doesn't actually work very well either, because it doesn't take into account the max range (aka limit).  So in other words, there are still scenarios where it breaks pagination.  It looks like there is a fix in the works though so it shouldn't be long.

**Comment by curquiza** [comment]
Hello @isaackearl!

Did you open an issue on the MeiliSearch repository?

FYI: `nbHits` is the total number of matches, and `hits.length` is the number of the query result (according to the limit you set or set by default).
