### ISSUE TITLE
Linter

### ISSUE THREAD

**Issue by curquiza** [shokme/laravel-scout-meilisearch#4]
We should have a linter so that everyone can easily contribute without messing the code 🙂

Steps:
- [ ] Add and configure the linter
- [ ] Add the command in README in the `Development Workflow` part
- [ ] Add it in GitHub Action to be triggered on each PR

**Comment by pet1330** [comment]
You can quickly automate this step by using [styleci](https://styleci.io/), it is free for opensource

**Comment by curquiza** [comment]
Thanks for the suggestion @pet1330! 😊

After discussing with the team, we would rather not to use styleCI since it needs to access to our organization content:
<img width="538" alt="Capture d’écran 2020-05-04 à 17 11 01" src="https://user-images.githubusercontent.com/20380692/81803347-d8a99400-9517-11ea-886d-3274f988f697.png">

We are going to install a basic linter like `php-cs-sniffer` (already used in the [PHP SDK](https://github.com/meilisearch/meilisearch-php)).
