### ISSUE TITLE
install error with laravel 7

### ISSUE THREAD

**Issue by dreamcog** [shokme/laravel-scout-meilisearch#43]
when i try to install  meilisearch-laravel-scout with laravel 7
it shows error:
```

composer require meilisearch/meilisearch-laravel-scout

Problem 1
    - Installation request for meilisearch/meilisearch-laravel-scout ^0.11.0 -> satisfiable by meilisearch/meilisearch-laravel-scout[v0.11.0].
    - Can only install one of: guzzlehttp/guzzle[6.5.x-dev, 7.0.1].
    - Can only install one of: guzzlehttp/guzzle[7.0.1, 6.5.x-dev].
    - Can only install one of: guzzlehttp/guzzle[6.5.x-dev, 7.0.1].
    - Conclusion: install guzzlehttp/guzzle 6.5.x-dev
    - Installation request for guzzlehttp/guzzle (locked at 7.0.1, required as ^7.0) -> satisfiable by guzzlehttp/guzzle[7.0.1].
```

**Comment by curquiza** [comment]
Hello @dreamcog!

This issue might be linked to this [issue in meilisearch-php](https://github.com/meilisearch/meilisearch-php/issues/76) and should be fixed soon. Tell me if I misunderstood your problem!

Thanks for your feedback and for trying MeilISearch 😁

**Comment by dreamcog** [comment]
@curquiza  thanks for your reply. 
i read the issue which was been post in meilisearch-php today , i will try to fix it myself :)

**Comment by curquiza** [comment]
Keep us informed about your fix! :)

**Comment by felixgoldstein** [comment]
same problem here. is there any quick solution?

**Comment by curquiza** [comment]
Hello @felixgoldstein! Sorry, I don't have any quick solution to provide right now. This PR https://github.com/meilisearch/meilisearch-php/pull/81 (that you might have already seen) will fix this issue. The new release containing this change will be available soon!

**Comment by ivang11** [comment]
@felixgoldstein I'm using the package with Laravel 7 you just have to use "guzzlehttp / guzzle": "^ 6.3" until this solved meilisearch/meilisearch-php#81

**Comment by rizalfauzie** [comment]
Make this support for older version of Laravel please.

**Comment by felixgoldstein** [comment]
@curquiza @IvanG11  i solved the issue for me by creating a fork of meilisearch-php and applying the open pull request on my fork - worked with laravel 8

**Comment by dreamcog** [comment]
i have solved it with @bensherred 's branch , thanks very much.

1.install the v0.14 melisearch-php
`$ composer require meilisearch/meilisearch-php symfony/http-client nyholm/psr7:^1.0`

2.install the @bensherred meilisearch-laravel-scout branch
`    
"repositories": [
        {
            "type"  : "vcs",
            "url"   : "https://github.com/bensherred/meilisearch-laravel-scout.git"
        }
    ]
`
and 
`        
"meilisearch/meilisearch-laravel-scout": "dev-update-meilisearch-php",
`

thanks @bensherred

**Comment by bensherred** [comment]
Hi @dreamcog, I wouldn't recommend using that approach. Although that's okay for testing the changes, it's not a permanent fix. I have a PR open which will fix this issue and merge my changes into this repo.

**Comment by curquiza** [comment]
The [v0.12.0](https://github.com/meilisearch/meilisearch-laravel-scout/releases/tag/v0.12.0) is now out and fixes this issue.

**Comment by rizalfauzie** [comment]
this is not fixed yet on **Laravel 7**

```
  Problem 1
    - Can only install one of: laravel/scout[8.x-dev, v7.2.1].
    - Can only install one of: laravel/scout[v7.2.1, 8.x-dev].
    - Can only install one of: laravel/scout[8.x-dev, v7.2.1].
    - meilisearch/meilisearch-laravel-scout v0.12.0 requires laravel/scout ^8.0 -> satisfiable by laravel/scout[8.x-dev].
    - Installation request for meilisearch/meilisearch-laravel-scout ^0.12.0 -> satisfiable by meilisearch/meilisearch-laravel-scout[v0.12.0].
    - Installation request for laravel/scout (locked at v7.2.1, required as ^7.2) -> satisfiable by laravel/scout[v7.2.1].

```

**Comment by bensherred** [comment]
@rizalfauzie can you send the contents of your composer.json dependencies?

**Comment by shokme** [comment]
> Installation request for laravel/scout (locked at v7.2.1, ...)

you probably need to upgrade your version of laravel scout to ^8 (required for meilisearch).
