### ISSUE TITLE
Missing results

### ISSUE THREAD

**Issue by ivang11** [shokme/laravel-scout-meilisearch#44]
I have tried with the movies.json example to test with the searches and if I look for the Ready Player One movie it does not find it. I have looked at the movies.json file and I found it, when importing it has been imported without problems.

I've been looking at the documentation but I can't see if the configuration needs to be adjusted, I was just with a project where I have a database with 486610 films with Laravel Scout and all of them are imported well and the same thing happened with the Ready Player film One so I have tried with the example.

**Comment by shokme** [comment]
Hello @IvanG11 

It works well on my side.
```php
$movies = Movie::search('Ready Player One')->raw();
dd($movies); // I can see Ready Player One
```
`->get()` return results from database where `->raw()` return results from meilisearch.

**Comment by ivang11** [comment]
Thanks for trying it @shokme 

I started the movie's example from scratch and now works well, maybe the first time fails something on the import
