### ISSUE TITLE
Create Wiki pages or any accessible docs

### ISSUE THREAD

**Issue by curquiza** [shokme/laravel-scout-meilisearch#46]
The purpose of this issue is to provide a Wiki documentation that cannot be written down in the README.
We could add a `How to` section to explain how to handles indexes, synonyms, and other settings even if it's not the first purpose of this package.

(Following this discussion on #45)

**Comment by curquiza** [comment]
Maybe you can be inspired by [Algolia's docs for their laravel-scout plugin](https://www.algolia.com/doc/framework-integration/laravel/getting-started/introduction-to-scout-extended/?language=php).

**Comment by shokme** [comment]
You can have a look to the wiki, I have added two possible way of handling indexes settings.

**Comment by curquiza** [comment]
Awesome! 🚀
