### ISSUE TITLE
PHP 7.2

### ISSUE THREAD

**Issue by curquiza** [shokme/laravel-scout-meilisearch#5]
A user asked us to support PHP 7.2:

<img width="886" alt="Capture d’écran 2020-04-19 à 22 50 49" src="https://user-images.githubusercontent.com/20380692/79699584-b1e99c00-8290-11ea-96a6-cdeaae3eb1e4.png">

What do you think @shokme? 🙂 Is it a huge work?

**Comment by lkmadushan** [comment]
@curquiza @shokme created a PR for this https://github.com/meilisearch/meilisearch-laravel-scout/pull/6

**Comment by shokme** [comment]
@curquiza It wasn't a huge work.

@lkmadushan Thank you for the PR :+1:

**Comment by curquiza** [comment]
Thanks guys 👍

**Comment by curquiza** [comment]
Closed with #6
