### ISSUE TITLE
Error when setup attributesToHighlight

### ISSUE THREAD

**Issue by anatoliy-t7** [shokme/laravel-scout-meilisearch#51]
I did:

```php
 Product::search($this->search, ['attributesToHighlight' => 'name'])->take(10)->get();
```

and I got this error:

```php
call_user_func() expects parameter 1 to be a valid callback, array must have exactly two members
```
![Screenshot](https://user-images.githubusercontent.com/11552252/94347444-d58bec00-0051-11eb-9637-cf699af78d65.png)

**Comment by shokme** [comment]
try this:
```php
Product::search($this->search, function (Indexes $meilisearch, $query, $options) {
    $options['attributesToHighlight'] = 'name';

    return $meilisearch->search($query, $options);
})->take(10)->get();
```

**Comment by anatoliy-t7** [comment]
> try this:
> 
> ```
> Product::search($this->search, function (Indexes $meilisearch, $query, $options) {
>     $options['attributesToHighlight'] = 'name';
> 
>     return $meilisearch->search($query, $options);
> })->take(10)->get();
> ```

Thank you for your reply but I get another error.

```php
Argument 1 passed to App\Http\Livewire\Site\SearchCom::App\Http\Livewire\Site\{closure}() must be an instance of App\Http\Livewire\Site\Indexes, instance of MeiliSearch\Endpoints\Indexes given
```
I know it happened because I use livewire and I tried to change it to:

```php
use MeiliSearch\Endpoints\Indexes as SearchIndexes;
//  . . . 
Product::search($this->search, function (SearchIndexes $meilisearch, $query, $options) {
    $options['attributesToHighlight'] = 'name';

    return $meilisearch->search($query, $options);
})->take(10)->get();
```
It  gave my:

```php
MeiliSearch\Exceptions\HTTPRequestException
Invalid JSON: invalid type: string "name", expected a sequence at line 1 column 106
```

![screen](https://user-images.githubusercontent.com/11552252/94386640-ceee9900-0165-11eb-90c8-0a97519da03c.png)

**Comment by shokme** [comment]
oh yes sorry, indeed I forgot to add an array `$options['attributesToHighlight'] = ['name'];`.
you can use the [documentation](https://docs.meilisearch.com/guides/advanced_guides/search_parameters.html#attributes-to-highlight), the callback content is always the same.

**Comment by anatoliy-t7** [comment]
Actually I can't get this content with `->get();` only by `->raw();`

**Comment by shokme** [comment]
> Actually I can't get this content with `->get();` only by `->raw();`

Yes, because `->get()` is doing a call in your database, like `select * from table where id in (result from meilisearch)`
and `->raw()` will show you the meilisearch response.
in your case you should use `->raw()` to display the highlighted word.

**Comment by anatoliy-t7** [comment]
Thanks for helping me and a good package.
