### ISSUE TITLE
Custom pagination with totalCount

### ISSUE THREAD

**Issue by vylink** [shokme/laravel-scout-meilisearch#60]
Hi,

I want to use "cursor" pagination with offset and limit.

How can I get the total count of documents in the following example?

```
        $result = Book::search('', function (Indexes $meilisearch, $query, $options) {
            $options['offset'] = 5;
            $options['limit'] = 30;
            return $meilisearch->search($query, $options);
        });

        return [
            'data' => $result->get(),
            'totalCount' => 0 // I want to know how many documents are in the index.
        ];
```

**Comment by shokme** [comment]
Hello @vylink,

I'm quite busy right now, I can't help you.

But I hope these indication can help you to solve your problem

`$result->get()` will show you the result from database, you should use `$result->raw()` to get the meilisearch response and have access to `nbHits`.

you also can do something like:
```
Book::getTotalCount($result->get())
```
[source](https://github.com/meilisearch/meilisearch-laravel-scout/blob/master/src/Engines/MeilisearchEngine.php#L196)

**Comment by curquiza** [comment]
Hello @shokme! Thanks for your help during your busy time! 🙂

Hi @vylink!
I would add some resources to complete the @shokme answer.
If you are building pagination, I really recommend you checking out this issue we (the Meili team) created to explain how MeiliSearch works with pagination: https://github.com/meilisearch/documentation/issues/561
Indeed `nbHits` (so `getTotalCount`) will not return the **exact** number of matches, if it's was you are looking for with `'totalCount' => 0 // I want to know how many documents are in the index`. You might build a pagination as explained in the first part of the issue.

Tell me if anything is not clear! And thanks for trying MeiliSearch with our laravel-scout plugin!!

**Comment by shokme** [comment]
@vylink did we resolve your issue ?

**Comment by vylink** [comment]
Many thanks for your recommendations
