### ISSUE TITLE
Master Key

### ISSUE THREAD

**Issue by EloFran** [shokme/laravel-scout-meilisearch#63]
Hi all, thx

I need someone to explain to me how I generate the master key and the others, I don't quite understand that part, I'm sorry.

thx

**Comment by curquiza** [comment]
Hello @EloFran!

You set the master key when running the MeiliSearch instance:

<img width="979" alt="Capture d’écran 2020-11-24 à 18 57 09" src="https://user-images.githubusercontent.com/20380692/100133301-dfca3b00-2e86-11eb-9d88-f8d0e7f5e244.png">

Here I set the master key to `random-key-with-salt`.
But, in production, you should set a more robust master key, like a big random and generated string.
Here more docs about authentication: https://docs.meilisearch.com/guides/advanced_guides/authentication.html
