### ISSUE TITLE
PHP 8 support

### ISSUE THREAD

**Issue by husonghua** [shokme/laravel-scout-meilisearch#64]
Hey, will this library add PHP 8 support soon?

**Comment by shokme** [comment]
Hello @husonghua 
I can start looking next week, but feel free to PR 😄

**Comment by shokme** [comment]
@husonghua 
I need to wait several libraries to be compatible with php 8
[laravel/scout](https://github.com/laravel/scout/pull/425) is waiting algolia https://github.com/algolia/algoliasearch-client-php/pull/644
I also need php-cs-fixer and I will see with the meilisearch-php sdk to support php 8

It will take more time than I thought. I'll update the issue once we are ready :smile:

**Comment by husonghua** [comment]
No problem. The laravel team mentioned the same thing about Scout and Algolia in their livestreaming.

**Comment by husonghua** [comment]
Looks like Scout has just updated to 8.5 to support php 8 😄

**Comment by marky291** [comment]
+1
