### ISSUE TITLE
Is the where method available?

### ISSUE THREAD

**Issue by Cannonb4ll** [shokme/laravel-scout-meilisearch#7]
Hi,

First of all, great work! 🤩

I wanted to ask if the basic `where()` method the original scout driver offers, is supported in this package as well?

If you read the original docs, it supports a basic where method:

```
Scout allows you to add simple "where" clauses to your search queries. Currently, these clauses only support basic numeric equality checks, and are primarily useful for scoping search queries by a tenant ID. Since a search index is not a relational database, more advanced "where" clauses are not currently supported
```

Docs:
https://laravel.com/docs/7.x/scout#where-clauses

Original method:
https://github.com/laravel/scout/blob/8.x/src/Engines/AlgoliaEngine.php#L156

Thanks!

**Comment by shokme** [comment]
Hello @Cannonb4ll,
Thank you !

The basic `where()` is not supported because MeiliSearch looks like to work a bit differently than Algolia.

I will do some R&D later this day, I'll keep you posted.

**Comment by Cannonb4ll** [comment]
Thank you! I might of be able to look into this soon myself as well and PR this for you.
