### ISSUE TITLE
Add tests for `search()` method

### ISSUE THREAD

**Issue by curquiza** [shokme/laravel-scout-meilisearch#81]
If I understand well, we don't have tests for the `search()` method:

https://github.com/meilisearch/meilisearch-laravel-scout/blob/a66ac4cca3ce5de66fa8e5cf0430ec28ac33c14c/src/Engines/MeilisearchEngine.php#L81-L92

We should add tests for this.

Tell me if I'm wrong 🙂

**Comment by shokme** [comment]
https://github.com/meilisearch/meilisearch-laravel-scout/blob/36d40eb69c156967c460f7605bd7d9cc63ad0f8f/tests/MeilisearchEngineTest.php#L47-L63
not sure to understand, this one is not enough?

**Comment by curquiza** [comment]
Maybe I badly understand I was surprised the `tests (PHP ...)` job did not break in this PR (https://github.com/meilisearch/meilisearch-laravel-scout/pull/70) before I changed the `search` into `rawSearch`.
For me, there was a lack of test, but again, maybe I missed something.

**Comment by mmachatschek** [comment]
@curquiza I think this should be solved or at least be covered by #102

**Comment by curquiza** [comment]
Yes! :)
If anyone thinks there are missing tests, feel free to open a new issue!
