### ISSUE TITLE
[Question] Custom search with where()

### ISSUE THREAD

**Issue by robsontenorio** [shokme/laravel-scout-meilisearch#99]
Hi,

I am trying to combine custom search with `where()`.

But the `->where('type_id', 3)` does not take effect

```php
 $result = Page::search('War', function (Indexes $meilisearch, $query, $options) {
            $options = ['attributesToHighlight' => ['description']];
            return $meilisearch->search($query, $options);
        })->where('type_id', 3)->raw();
```

If i do a simple search it works as expected. But, for sure, i dont get hililght anymore.

```php
 $result = Page::search('War')->where('type_id', 3)->raw();
```

**Comment by curquiza** [comment]
Hello @robsontenorio!
What is the version of meilisearch-laravel-scout you are using?
Can you check from 0.12.1 and later and tell us when you have this failure? Thanks a lot, it would be really helpful!
https://github.com/meilisearch/meilisearch-laravel-scout/releases

**Comment by robsontenorio** [comment]
@curquiza 

Just  noticed i cant combine other methods like `->take()` with custom search. Is that expected?

docker image: meilisearch:v0.18.1

composer: meilisearch-laravel-scout": "^0.12.4",         "laravel/scout": "^8.6",         "laravel/framework": "^8.12"

```
use Illuminate\Database\Eloquent\Model;
use Laravel\Scout\Searchable;

class Page extends Model
{
    use Searchable;

}
```

**Comment by curquiza** [comment]
I don't think this is expected (can you confirm @shokme?)

@robsontenorio, can you check if it works (or not) with previous versions, like the v0.12.1 for example? Thanks!

**Comment by robsontenorio** [comment]
@curquiza  No lucky at 0.12.1 :( Same issue.

**Comment by robsontenorio** [comment]
I am sorry! Wrong array syntaxe ... My bad!

Wrong
```php
            $options = ['attributesToHighlight' => ['description']];

```

Right
```php
            $options['attributesToHighlight'] = ['description'];

```
